ALTER TABLE SWMS.MN_ROLE_USER_ASSIGNMENT
 ADD CONSTRAINT CONST_ROLE_ROLE_USER_ASS_FK
 FOREIGN KEY (ROLE_ID)
 REFERENCES SWMS.DAT_ROLE (ID) ENABLE
 VALIDATE
 
 ALTER TABLE SWMS.MN_ROLE_USER_ASSIGNMENT
 ADD CONSTRAINT CONST_ROLE_USER_ASS_USER_FK
 FOREIGN KEY (USER_ID)
 REFERENCES SWMS.DAT_USER (ID) ENABLE
 VALIDATE
 
 ALTER TABLE SWMS.DAT_ACTIVITY_STATUS
 ADD CONSTRAINT CONST_USER_ACTIVITY_STATUS_FK
 FOREIGN KEY (USER_ID)
 REFERENCES SWMS.DAT_USER (ID) ENABLE
 VALIDATE
 
 ALTER TABLE SWMS.MN_ROLE_ACTIVITY_ASSIGNMENT
 ADD CONSTRAINT CONST_ROLE_ACT_ACT_FK
 FOREIGN KEY (ACTIVITY_ID)
 REFERENCES SWMS.DAT_ACTIVITY (ID) ENABLE
 VALIDATE
 
 ALTER TABLE SWMS.DAT_ACTIVITY
 ADD CONSTRAINT CONST_ACT_WF_SCHEME_FK
 FOREIGN KEY (WORKFLOW_SCHEME_ID)
 REFERENCES SWMS.DAT_WORKFLOW_SCHEME (ID) ENABLE
 VALIDATE
 
 ALTER TABLE SWMS.DAT_WORKFLOW
 ADD CONSTRAINT CONST_WF_SCHEME_WF_FK
 FOREIGN KEY (WORFLOW_SCHEME_ID)
 REFERENCES SWMS.DAT_WORKFLOW_SCHEME (ID) ENABLE
 VALIDATE

 ALTER TABLE SWMS.DAT_ACTIVITY_STATUS
 ADD CONSTRAINT CONST_ACT_STATUS_WF_FK
 FOREIGN KEY (WORKFLOW_ID)
 REFERENCES SWMS.DAT_WORKFLOW (ID) ENABLE
 VALIDATE
 
 ALTER TABLE SWMS.DAT_ACTIVITY_STATUS
 ADD CONSTRAINT CONST_ACT_STATUS_ACT_FK
 FOREIGN KEY (ACTIVITY_ID)
 REFERENCES SWMS.DAT_ACTIVITY (ID) ENABLE
 VALIDATE
 
 ALTER TABLE SWMS.DAT_ACTIVITY_FLOW
 ADD CONSTRAINT CONST_ACT_ACT_FLOW_FK1
 FOREIGN KEY (ACTIVITY_ID)
 REFERENCES SWMS.DAT_ACTIVITY (ID) ENABLE
 VALIDATE
 
 ALTER TABLE SWMS.DAT_ACTIVITY_FLOW
 ADD CONSTRAINT CONST_ACT_ACT_FLOW_FK2
 FOREIGN KEY (PREDECESSOR_ID)
 REFERENCES SWMS.DAT_ACTIVITY (ID) ENABLE
 VALIDATE
 